
name: Maven Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: docker build -t calculator .

    - name: Bump Version
      id: bump
      uses: nnichols/maven-version-bump-action@v3
      with:
        github-token: ${{ secrets.github_token }}

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: tag image
      run: docker tag calculator ${{ secrets.DOCKER_USERNAME }}/calculator:${{steps.bump.outputs.version}}

    - name: Publish Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/calculator:${{steps.bump.outputs.version}}
